name: Update Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'wiki/**'

permissions:
  contents: write

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Upload Wiki Content
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: wiki
          commit-message: "docs: update wiki content"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
