name: Update Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'wiki/**'


permissions:
  contents: read
  pages: write


jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        with:
          fetch-depth: 0

      - name: Upload Wiki Content
        uses: SwiftDocOrg/github-wiki-publish-action@98d0d21e4c8f4d7c7bef2e2dc8449b4c4c888878
        with:
          path: "wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 
